/*
 * Template:
 * {
 * 		"relationshipKey1": "relationshipName1",
 * 		"relationshipKey3": "relationshipName2",
 * 		...
 * }
 */

var relationshipsKeys =
{
	"a" : "access",
	"c" : "composition",
	"f"	: "flow",
	"g" : "aggregation",
	"i" : "assignment",
	"n" : "influence",
	"o" : "association",
	"r" : "realisation",
	"s" : "specialisation",
	"t" : "triggering",
	"u" : "usedBy",
};

/*
 * Template:
 * {
 * 		"source": {
 * 			"target": ["relationshipKey1", relationshipKey2", ...],
 * 			"target": ["relationshipKey1", relationshipKey2", ...],
 * 			...
 * 		},
 * 		"source": {
 * 			"target": ["relationshipKey1", relationshipKey2", ...],
 * 			"target": ["relationshipKey1", relationshipKey2", ...],
 * 			...
 * 		},
 * ...
 * }
 */

var relationships = 
{
	 "BusinessActor" : {
		 
		 "BusinessActor": ["c","f","g","o","s","t","u"],
		 "BusinessRole": ["f","i","o","t","u"],
		 "BusinessCollaboration": ["f","i","o","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["c","f","i","o","t","u"],
		 "BusinessProcess": ["f","i","o","t","u"],
		 "BusinessFunction": ["f","i","o","t","u"],
		 "BusinessInteraction": ["c","f","i","o","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["i","o","r","u"],
		 "BusinessObject": ["a", "o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a", "o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["f","o","t"],
		 "ApplicationCollaboration": ["f","o","t"],
		 "ApplicationInterface": ["f","o","t"],
		 "ApplicationFunction": ["f","o","t"],
		 "ApplicationInteraction": ["f","o","t"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["i","o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["i","o","f","t"],
		 "Deliverable": ["o","r"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessRole" : {
		 
		 "BusinessActor": ["f","o","t","u"],
		 "BusinessRole": ["c","f","g","o","s","t","u"],
		 "BusinessCollaboration": ["c","f","g","o","s","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["c","f","g","i","o","t","u"],
		 "BusinessProcess": ["f","i","o","t","u"],
		 "BusinessFunction": ["f","i","o","t","u"],
		 "BusinessInteraction": ["f","i","o","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["i","o","r","u"],
		 "BusinessObject": ["a", "o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a", "o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["f","o","t"],
		 "ApplicationCollaboration": ["f","o","t"],
		 "ApplicationInterface": ["f","o","t"],
		 "ApplicationFunction": ["f","o","t"],
		 "ApplicationInteraction": ["f","o","t"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["i","o","f","t"],
		 "Deliverable": ["o","r"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessCollaboration" : {
		 
		 "BusinessActor": ["f","g","o","t","u"],
		 "BusinessRole": ["c","f","g","o","s","t","u"],
		 "BusinessCollaboration": ["c","f","g","o","s","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["c","f","g","o","t","u"],
		 "BusinessProcess": ["f","i","o","t","u"],
		 "BusinessFunction": ["f","i","o","t","u"],
		 "BusinessInteraction": ["f","i","o","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["i","o","r","u"],
		 "BusinessObject": ["a", "o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a", "o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["f","o","t"],
		 "ApplicationCollaboration": ["f","o","t"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["f","o","t"],
		 "ApplicationInteraction": ["f","o","t"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "Location" : {
		 
		 "BusinessActor": ["f","i","o","t","u"],
		 "BusinessRole": ["f","i","o","t","u"],
		 "BusinessCollaboration": ["f","i","o","t","u"],
		 "Location": ["c","f","g","o","t","u"],
		 "BusinessInterface": ["f","i","o","t","u"],
		 "BusinessProcess": ["i","o"],
		 "BusinessFunction": ["f","i","o","t","u"],
		 "BusinessInteraction": ["i","o"],
		 "BusinessEvent": ["i","o","t"],
		 "BusinessService": ["i","o"],
		 "BusinessObject": ["i","o"],
		 "Representation": ["i","o"],
		 "Product": ["o"],
		 "Contract": ["i","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["i","o"],
		 "ApplicationCollaboration": ["i","o"],
		 "ApplicationInterface": ["i","o"],
		 "ApplicationFunction": ["i","o"],
		 "ApplicationInteraction": ["i","o"],
		 "ApplicationService": ["i","o"],
		 "DataObject": ["i","o"],
		 
		 "Node": ["i","o"],
		 "Device": ["i","o"],
		 "SystemSoftware": ["i","o"],
		 "InfrastructureInterface": ["i","o"],
		 "Network": ["i","o"],
		 "CommunicationPath": ["i","o"],
		 "InfrastructureFunction": ["i","o"],
		 "InfrastructureService": ["i","o"],
		 "Artifact": ["i","o"],
		 
		 "Stakeholder": ["i","o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["i","o"],
		 "Deliverable": ["i","o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessInterface" : {
		 
		 "BusinessActor": ["f","o","t","u"],
		 "BusinessRole": ["f","o","t","u"],
		 "BusinessCollaboration": ["f","o","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["c","f","g","o","s","t","u"],
		 "BusinessProcess": ["o","u"],
		 "BusinessFunction": ["o","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["i","o","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessProcess" : {
		 
		 "BusinessActor": ["f","o","t","u"],
		 "BusinessRole": ["f","o","t","u"],
		 "BusinessCollaboration": ["f","o","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["c","f","g","o","s","t","u"],
		 "BusinessFunction": ["c","f","g","o","s","t","u"],
		 "BusinessInteraction": ["c","f","g","o","s","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["f","o","r","t","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["f","o","t"],
		 "ApplicationCollaboration": ["f","o","t"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessFunction" : {
		 
		 "BusinessActor": ["f","o","t","u"],
		 "BusinessRole": ["f","o","t","u"],
		 "BusinessCollaboration": ["f","o","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["c","f","g","o","s","t","u"],
		 "BusinessFunction": ["c","f","g","o","s","t","u"],
		 "BusinessInteraction": ["c","f","g","o","s","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["f","o","r","t","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["f","o","t"],
		 "ApplicationCollaboration": ["f","o","t"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessInteraction" : {
		 
		 "BusinessActor": ["f","o","t","u"],
		 "BusinessRole": ["f","o","t","u"],
		 "BusinessCollaboration": ["f","o","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["c","f","g","o","s","t","u"],
		 "BusinessFunction": ["c","f","g","o","s","t","u"],
		 "BusinessInteraction": ["c","f","g","o","s","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["f","o","r","t","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["f","o","t"],
		 "ApplicationCollaboration": ["f","o","t"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessEvent" : {
		 
		 "BusinessActor": ["o","t"],
		 "BusinessRole": ["o","t"],
		 "BusinessCollaboration": ["o","t"],
		 "Location": ["o","t"],
		 "BusinessInterface": ["o","t"],
		 "BusinessProcess": ["o","t"],
		 "BusinessFunction": ["o","t"],
		 "BusinessInteraction": ["o","t"],
		 "BusinessEvent": ["c","g","o","s","t"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","t"],
		 "ApplicationCollaboration": ["o","t"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["t"],
	 },
	 
	 "BusinessService" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["f","o","t","u"],
		 "BusinessFunction": ["f","o","t","u"],
		 "BusinessInteraction": ["f","o","t","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["c","f","g","o","s","t","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "BusinessObject" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["c","g","o","s"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["c","g","o","s"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Representation" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o","r"],
		 "Representation": ["c","g","o","s"],
		 "Product": ["o"],
		 "Contract": ["o","r"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Product" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","u"],
		 "BusinessFunction": ["o","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["g","o","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["c","g","o","s"],
		 "Contract": ["a","g","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","u"],
		 "ApplicationCollaboration": ["o","u"],
		 "ApplicationInterface": ["o","u"],
		 "ApplicationFunction": ["o","u"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["g","o","u"],
		 "DataObject": ["a","o"],
		 
		 "Node": ["o","u"],
		 "Device": ["o","u"],
		 "SystemSoftware": ["o","u"],
		 "InfrastructureInterface": ["o","u"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o","u"],
		 "InfrastructureService": ["g","o","u"],
		 "Artifact": ["a","o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Contract" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["c","g","o","s"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["c","g","o","s"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Meaning" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Meaning": ["c","g","o","s"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
	 },
	 
	 "Value" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Meaning": ["o"],
		 "Value": ["c","g","o","s"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o"],
		 "Requirement": ["o"],
		 "Principle": ["o"],
		 "Constraint": ["o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "ApplicationComponent" : {
		 
		 "BusinessActor": ["f","o","t","u"],
		 "BusinessRole": ["f","o","t","u"],
		 "BusinessCollaboration": ["f","o","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["f","i","o","t","u"],
		 "BusinessFunction": ["f","i","o","t","u"],
		 "BusinessInteraction": ["f","i","o","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["i","o","r","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["c","f","g","o","s","t","u"],
		 "ApplicationCollaboration": ["c","f","g","o","s","t","u"],
		 "ApplicationInterface": ["c","f","g","o","t","u"],
		 "ApplicationFunction": ["i","o","u"],
		 "ApplicationInteraction": ["i","o","u"],
		 "ApplicationService": ["i","o","r","u"],
		 "DataObject": ["a","o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },

	 "ApplicationCollaboration" : {
		 
		 "BusinessActor": ["f","o","t","u"],
		 "BusinessRole": ["f","o","t","u"],
		 "BusinessCollaboration": ["f","o","t","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["f","i","o","t","u"],
		 "BusinessFunction": ["f","i","o","t","u"],
		 "BusinessInteraction": ["f","i","o","t","u"],
		 "BusinessEvent": ["o","t"],
		 "BusinessService": ["i","o","r","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["c","f","g","o","s","t","u"],
		 "ApplicationCollaboration": ["c","f","g","o","s","t","u"],
		 "ApplicationInterface": ["c","f","g","o","t","u"],
		 "ApplicationFunction": ["i","o","u"],
		 "ApplicationInteraction": ["i","o","u"],
		 "ApplicationService": ["i","o","r","u"],
		 "DataObject": ["a","o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },

	 "ApplicationInterface" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["f","o","t","u"],
		 "BusinessFunction": ["f","o","t","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["i","o","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["f","o","t","u"],
		 "ApplicationCollaboration": ["f","o","t","u"],
		 "ApplicationInterface": ["c","f","g","o","s","t","u"],
		 "ApplicationFunction": ["o","u"],
		 "ApplicationInteraction": ["o","u"],
		 "ApplicationService": ["i","o","u"],
		 "DataObject": ["a","o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "ApplicationFunction" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["f","o","t","u"],
		 "BusinessFunction": ["o","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","u"],
		 "ApplicationCollaboration": ["o","u"],
		 "ApplicationInterface": ["o","u"],
		 "ApplicationFunction": ["c","f","g","o","s","t","u"],
		 "ApplicationInteraction": ["f","o","t"],
		 "ApplicationService": ["f","o","r","t","u"],
		 "DataObject": ["a","o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "ApplicationInteraction" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["f","o","t","u"],
		 "BusinessProcess": ["f","o","t","u"],
		 "BusinessFunction": ["o","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","u"],
		 "ApplicationCollaboration": ["o","u"],
		 "ApplicationInterface": ["o","u"],
		 "ApplicationFunction": ["f","o","t","u"],
		 "ApplicationInteraction": ["c","f","g","o","s","t"],
		 "ApplicationService": ["o","r","u"],
		 "DataObject": ["a","o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "ApplicationService" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","u"],
		 "BusinessFunction": ["o","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","u"],
		 "BusinessObject": ["a","o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","u"],
		 "ApplicationCollaboration": ["o","u"],
		 "ApplicationInterface": ["o","u"],
		 "ApplicationFunction": ["f","o","r","t","u"],
		 "ApplicationInteraction": ["o","u"],
		 "ApplicationService": ["c","f","g","o","s","t","u"],
		 "DataObject": ["a","o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "DataObject" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o","r"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o","r"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["c","g","o","s"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Node" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","r","u"],
		 "BusinessFunction": ["o","r","u"],
		 "BusinessInteraction": ["o","r","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","r","u"],
		 "BusinessObject": ["a","o","r","u"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o","r","u"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["a","o","r","u"],
		 "ApplicationCollaboration": ["a","o","r","u"],
		 "ApplicationInterface": ["a","o","r","u"],
		 "ApplicationFunction": ["a","o","r","u"],
		 "ApplicationInteraction": ["a","o","r","u"],
		 "ApplicationService": ["a","o","r","u"],
		 "DataObject": ["a","o","r","u"],
		 
		 "Node": ["c","f","g","o","s","t","u"],
		 "Device": ["c","f","g","o","s","t","u"],
		 "SystemSoftware": ["c","f","g","o","s","t","u"],
		 "InfrastructureInterface": ["c","f","g","o","t","u"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["i","o","u"],
		 "InfrastructureService": ["a","i","o","u"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "Device" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","r","u"],
		 "BusinessFunction": ["o","r","u"],
		 "BusinessInteraction": ["o","r","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","r","u"],
		 "BusinessObject": ["a","o","r","u"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o","r","u"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["a","o","r","u"],
		 "ApplicationCollaboration": ["a","o","r","u"],
		 "ApplicationInterface": ["a","o","r","u"],
		 "ApplicationFunction": ["a","o","r","u"],
		 "ApplicationInteraction": ["a","o","r","u"],
		 "ApplicationService": ["a","o","r","u"],
		 "DataObject": ["a","o","r","u"],
		 
		 "Node": ["c","f","g","o","s","t","u"],
		 "Device": ["c","f","g","o","s","t","u"],
		 "SystemSoftware": ["c","f","g","i","o","s","t","u"],
		 "InfrastructureInterface": ["c","f","g","o","t","u"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["i","o","u"],
		 "InfrastructureService": ["i","o","r","u"],
		 "Artifact": ["a","i","o","u"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "SystemSoftware" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","r","u"],
		 "BusinessFunction": ["o","r","u"],
		 "BusinessInteraction": ["o","r","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","r","u"],
		 "BusinessObject": ["a","o","r","u"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o","r","u"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["a","o","r","u"],
		 "ApplicationCollaboration": ["a","o","r","u"],
		 "ApplicationInterface": ["a","o","r","u"],
		 "ApplicationFunction": ["a","o","r","u"],
		 "ApplicationInteraction": ["a","o","r","u"],
		 "ApplicationService": ["a","o","r","u"],
		 "DataObject": ["a","o","r","u"],
		 
		 "Node": ["c","f","g","o","s","t","u"],
		 "Device": ["c","f","g","o","s","t","u"],
		 "SystemSoftware": ["c","f","g","o","s","t","u"],
		 "InfrastructureInterface": ["c","f","g","o","t","u"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["i","o","u"],
		 "InfrastructureService": ["i","o","r","u"],
		 "Artifact": ["a","i","o","u"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "InfrastructureInterface" : {
		 
		 "BusinessActor": ["a","o","u"],
		 "BusinessRole": ["a","o","u"],
		 "BusinessCollaboration": ["a","o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["a","o","u"],
		 "BusinessProcess": ["a","o","u"],
		 "BusinessFunction": ["a","o","u"],
		 "BusinessInteraction": ["a","o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["a","o","u"],
		 "BusinessObject": ["a","o","u"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o","u"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["a","o","u"],
		 "ApplicationCollaboration": ["a","o","u"],
		 "ApplicationInterface": ["a","o","u"],
		 "ApplicationFunction": ["a","o","u"],
		 "ApplicationInteraction": ["a","o","u"],
		 "ApplicationService": ["a","o","u"],
		 "DataObject": ["a","o","u"],
		 
		 "Node": ["f","o","t","u"],
		 "Device": ["f","o","t","u"],
		 "SystemSoftware": ["f","o","t","u"],
		 "InfrastructureInterface": ["c","f","g","o","s","t","u"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o","u"],
		 "InfrastructureService": ["i","o","u"],
		 "Artifact": ["a","o","u"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },
	 
	 "Network" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["c","g","o","s"],
		 "CommunicationPath": ["o","r"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 

	 "CommunicationPath" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["c","g","o","s"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },

	 "InfrastructureFunction" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","u"],
		 "BusinessFunction": ["o","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","u"],
		 "BusinessObject": ["a","o","u"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o","u"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["a","o","u"],
		 "ApplicationCollaboration": ["a","o","u"],
		 "ApplicationInterface": ["a","o","u"],
		 "ApplicationFunction": ["a","o","u"],
		 "ApplicationInteraction": ["a","o","u"],
		 "ApplicationService": ["a","o","u"],
		 "DataObject": ["a","o","u"],
		 
		 "Node": ["o","u"],
		 "Device": ["o","u"],
		 "SystemSoftware": ["o","u"],
		 "InfrastructureInterface": ["o","u"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["c","f","g","o","s","t","u"],
		 "InfrastructureService": ["o","r","u"],
		 "Artifact": ["a","o","u"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],

		 "Junction": ["f","t"],
	 },

	 "InfrastructureService" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","u"],
		 "BusinessFunction": ["o","u"],
		 "BusinessInteraction": ["o","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","u"],
		 "BusinessObject": ["a","o","u"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o","u"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","u"],
		 "ApplicationCollaboration": ["o","u"],
		 "ApplicationInterface": ["o","u"],
		 "ApplicationFunction": ["o","u"],
		 "ApplicationInteraction": ["o","u"],
		 "ApplicationService": ["o","u"],
		 "DataObject": ["a","o","u"],
		 
		 "Node": ["o","u"],
		 "Device": ["o","u"],
		 "SystemSoftware": ["o","u"],
		 "InfrastructureInterface": ["o","u"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o","u"],
		 "InfrastructureService": ["c","f","g","o","s","t","u"],
		 "Artifact": ["a","o","u"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],

		 "Junction": ["f","t"],
	 },

	 "Artifact" : {
		 
		 "BusinessActor": ["o","u"],
		 "BusinessRole": ["o","u"],
		 "BusinessCollaboration": ["o","u"],
		 "Location": ["o"],
		 "BusinessInterface": ["o","u"],
		 "BusinessProcess": ["o","r","u"],
		 "BusinessFunction": ["o","r","u"],
		 "BusinessInteraction": ["o","r","u"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o","r","u"],
		 "BusinessObject": ["a","o","r"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["a","o","r"],
		 "Meaning": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","r","u"],
		 "ApplicationCollaboration": ["o","r","u"],
		 "ApplicationInterface": ["o","r","u"],
		 "ApplicationFunction": ["o","r","u"],
		 "ApplicationInteraction": ["o","r","u"],
		 "ApplicationService": ["o","r","u"],
		 "DataObject": ["a","o","r"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o","r"],
		 "InfrastructureInterface": ["o","r"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o","r"],
		 "InfrastructureService": ["o","r"],
		 "Artifact": ["c","g","o","r","s"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Stakeholder" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["c","g","o","s"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o"],
		 "Requirement": ["o"],
		 "Principle": ["o"],
		 "Constraint": ["o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Driver" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["c","g","n","o","s"],
		 "Assessment": ["n","o"],
		 "Goal": ["n","o"],
		 "Requirement": ["n","o"],
		 "Principle": ["n","o"],
		 "Constraint": ["n","o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Assessment" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["n","o"],
		 "Assessment": ["c","g","n","o","s"],
		 "Goal": ["n","o"],
		 "Requirement": ["n","o"],
		 "Principle": ["n","o"],
		 "Constraint": ["n","o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Goal" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["n","o"],
		 "Assessment": ["n","o"],
		 "Goal": ["c","g","n","o","s"],
		 "Requirement": ["n","o"],
		 "Principle": ["n","o"],
		 "Constraint": ["n","o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Assessment" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["n","o"],
		 "Assessment": ["n","o"],
		 "Goal": ["c","g","n","o","s"],
		 "Requirement": ["n","o"],
		 "Principle": ["n","o"],
		 "Constraint": ["n","o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },
	 
	 "Requirement" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["n","o"],
		 "Assessment": ["n","o"],
		 "Goal": ["n","o","r"],
		 "Requirement": ["c","g","n","o","s"],
		 "Principle": ["n","o","r"],
		 "Constraint": ["c","g","n","o","s"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },

	 "Principle" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["n","o"],
		 "Assessment": ["n","o"],
		 "Goal": ["n","o","r"],
		 "Requirement": ["n","o"],
		 "Principle": ["c","g","n","o","s"],
		 "Constraint": ["n","o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },

	 "Constraint" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["n","o"],
		 "Assessment": ["n","o"],
		 "Goal": ["n","o","r"],
		 "Requirement": ["c","g","n","o","s"],
		 "Principle": ["n","o","r"],
		 "Constraint": ["c","g","n","o","s"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["o"],
	 },

	 "WorkPackage" : {
		 
		 "BusinessActor": ["f","o","r","t"],
		 "BusinessRole": ["f","o","r","t"],
		 "BusinessCollaboration": ["o","r"],
		 "Location": ["o","r"],
		 "BusinessInterface": ["o","r"],
		 "BusinessProcess": ["o","r"],
		 "BusinessFunction": ["o","r"],
		 "BusinessInteraction": ["o","r"],
		 "BusinessEvent": ["o","r"],
		 "BusinessService": ["o","r"],
		 "BusinessObject": ["o","r"],
		 "Representation": ["o","r"],
		 "Product": ["o","r"],
		 "Contract": ["o","r"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","r"],
		 "ApplicationCollaboration": ["o","r"],
		 "ApplicationInterface": ["o","r"],
		 "ApplicationFunction": ["o","r"],
		 "ApplicationInteraction": ["o","r"],
		 "ApplicationService": ["o","r"],
		 "DataObject": ["o","r"],
		 
		 "Node": ["o","r"],
		 "Device": ["o","r"],
		 "SystemSoftware": ["o","r"],
		 "InfrastructureInterface": ["o","r"],
		 "Network": ["o","r"],
		 "CommunicationPath": ["o","r"],
		 "InfrastructureFunction": ["o","r"],
		 "InfrastructureService": ["o","r"],
		 "Artifact": ["o","r"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["c","f","g","o","s","t"],
		 "Deliverable": ["o","r"],
		 "Plateau": ["o","r"],
		 "Gap": ["o"],
		 
		 "Junction": ["f","t"],
	 },

	 "Deliverable" : {
		 
		 "BusinessActor": ["o","r"],
		 "BusinessRole": ["o","r"],
		 "BusinessCollaboration": ["o","r"],
		 "Location": ["o","r"],
		 "BusinessInterface": ["o","r"],
		 "BusinessProcess": ["o","r"],
		 "BusinessFunction": ["o","r"],
		 "BusinessInteraction": ["o","r"],
		 "BusinessEvent": ["o","r"],
		 "BusinessService": ["o","r"],
		 "BusinessObject": ["o","r"],
		 "Representation": ["o","r"],
		 "Product": ["o","r"],
		 "Contract": ["o","r"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o","r"],
		 "ApplicationCollaboration": ["o","r"],
		 "ApplicationInterface": ["o","r"],
		 "ApplicationFunction": ["o","r"],
		 "ApplicationInteraction": ["o","r"],
		 "ApplicationService": ["o","r"],
		 "DataObject": ["o","r"],
		 
		 "Node": ["o","r"],
		 "Device": ["o","r"],
		 "SystemSoftware": ["o","r"],
		 "InfrastructureInterface": ["o","r"],
		 "Network": ["o","r"],
		 "CommunicationPath": ["o","r"],
		 "InfrastructureFunction": ["o","r"],
		 "InfrastructureService": ["o","r"],
		 "Artifact": ["o","r"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o","r"],
		 "Requirement": ["o","r"],
		 "Principle": ["o","r"],
		 "Constraint": ["o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["c","g","o","s"],
		 "Plateau": ["o","r"],
		 "Gap": ["o"],
	 },
	 
	 "Plateau" : {
		 
		 "BusinessActor": ["g","o"],
		 "BusinessRole": ["g","o"],
		 "BusinessCollaboration": ["g","o"],
		 "Location": ["g","o"],
		 "BusinessInterface": ["g","o"],
		 "BusinessProcess": ["g","o"],
		 "BusinessFunction": ["g","o"],
		 "BusinessInteraction": ["g","o"],
		 "BusinessEvent": ["g","o"],
		 "BusinessService": ["g","o"],
		 "BusinessObject": ["g","o"],
		 "Representation": ["g","o"],
		 "Product": ["g","o"],
		 "Contract": ["g","o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["g","o"],
		 "ApplicationCollaboration": ["g","o"],
		 "ApplicationInterface": ["g","o"],
		 "ApplicationFunction": ["g","o"],
		 "ApplicationInteraction": ["g","o"],
		 "ApplicationService": ["g","o"],
		 "DataObject": ["g","o"],
		 
		 "Node": ["g","o"],
		 "Device": ["g","o"],
		 "SystemSoftware": ["g","o"],
		 "InfrastructureInterface": ["g","o"],
		 "Network": ["g","o"],
		 "CommunicationPath": ["g","o"],
		 "InfrastructureFunction": ["g","o"],
		 "InfrastructureService": ["g","o"],
		 "Artifact": ["g","o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["g","o","r"],
		 "Requirement": ["g","o","r"],
		 "Principle": ["o"],
		 "Constraint": ["g","o","r"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["c","g","o","s","t"],
		 "Gap": ["o"],
		 
		 "Junction": ["t"],
	 },
	 
	 "Gap" : {
		 
		 "BusinessActor": ["o"],
		 "BusinessRole": ["o"],
		 "BusinessCollaboration": ["o"],
		 "Location": ["o"],
		 "BusinessInterface": ["o"],
		 "BusinessProcess": ["o"],
		 "BusinessFunction": ["o"],
		 "BusinessInteraction": ["o"],
		 "BusinessEvent": ["o"],
		 "BusinessService": ["o"],
		 "BusinessObject": ["o"],
		 "Representation": ["o"],
		 "Product": ["o"],
		 "Contract": ["o"],
		 "Value": ["o"],
		        
		 "ApplicationComponent": ["o"],
		 "ApplicationCollaboration": ["o"],
		 "ApplicationInterface": ["o"],
		 "ApplicationFunction": ["o"],
		 "ApplicationInteraction": ["o"],
		 "ApplicationService": ["o"],
		 "DataObject": ["o"],
		 
		 "Node": ["o"],
		 "Device": ["o"],
		 "SystemSoftware": ["o"],
		 "InfrastructureInterface": ["o"],
		 "Network": ["o"],
		 "CommunicationPath": ["o"],
		 "InfrastructureFunction": ["o"],
		 "InfrastructureService": ["o"],
		 "Artifact": ["o"],
		 
		 "Stakeholder": ["o"],
		 "Driver": ["o"],
		 "Assessment": ["o"],
		 "Goal": ["o"],
		 "Requirement": ["o"],
		 "Principle": ["o"],
		 "Constraint": ["o"],

		 "WorkPackage": ["o"],
		 "Deliverable": ["o"],
		 "Plateau": ["o"],
		 "Gap": ["c","g","o","s"],
	 },
	 
	 "Junction" : {
		 
		 "BusinessActor": ["f","t"],
		 "BusinessRole": ["f","t"],
		 "BusinessCollaboration": ["f","t"],
		 "Location": ["f","t"],
		 "BusinessInterface": ["f","t"],
		 "BusinessProcess": ["f","t"],
		 "BusinessFunction": ["f","t"],
		 "BusinessInteraction": ["f","t"],
		 "BusinessEvent": ["t"],
		 "BusinessService": ["f","t"],
		        
		 "ApplicationComponent": ["f","t"],
		 "ApplicationCollaboration": ["f","t"],
		 "ApplicationInterface": ["f","t"],
		 "ApplicationFunction": ["f","t"],
		 "ApplicationInteraction": ["f","t"],
		 "ApplicationService": ["f","t"],
		 
		 "Node": ["f","t"],
		 "Device": ["f","t"],
		 "SystemSoftware": ["f","t"],
		 "InfrastructureInterface": ["f","t"],
		 "InfrastructureFunction": ["f","t"],
		 "InfrastructureService": ["f","t"],

		 "WorkPackage": ["f","t"],
		 "Plateau": ["t"],

		 "Junction": ["f","t"],
	 },
}

